# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\User\Desktop\Hw1\Dataset_OpenCvDl_Hw1\Dataset_OpenCvDl_Hw1\hw1_gui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 30, 161, 521))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignTop)
        self.pushButton_1_1 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_1_1.setObjectName("pushButton_1_1")
        self.verticalLayout.addWidget(self.pushButton_1_1, 0, QtCore.Qt.AlignTop)
        self.pushButton_1_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_1_2.setObjectName("pushButton_1_2")
        self.verticalLayout.addWidget(self.pushButton_1_2, 0, QtCore.Qt.AlignTop)
        self.pushButton_1_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_1_3.setObjectName("pushButton_1_3")
        self.verticalLayout.addWidget(self.pushButton_1_3, 0, QtCore.Qt.AlignTop)
        self.pushButton_1_4 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_1_4.setObjectName("pushButton_1_4")
        self.verticalLayout.addWidget(self.pushButton_1_4, 0, QtCore.Qt.AlignTop)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(220, 30, 160, 521))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2, 0, QtCore.Qt.AlignTop)
        self.pushButton_2_1 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_2_1.setObjectName("pushButton_2_1")
        self.verticalLayout_2.addWidget(self.pushButton_2_1, 0, QtCore.Qt.AlignTop)
        self.pushButton_2_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_2_2.setObjectName("pushButton_2_2")
        self.verticalLayout_2.addWidget(self.pushButton_2_2, 0, QtCore.Qt.AlignTop)
        self.pushButton_2_3 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_2_3.setObjectName("pushButton_2_3")
        self.verticalLayout_2.addWidget(self.pushButton_2_3, 0, QtCore.Qt.AlignTop)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(410, 30, 160, 521))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3, 0, QtCore.Qt.AlignTop)
        self.pushButton_3_1 = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_3_1.setObjectName("pushButton_3_1")
        self.verticalLayout_3.addWidget(self.pushButton_3_1, 0, QtCore.Qt.AlignTop)
        self.pushButton_3_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_3_2.setObjectName("pushButton_3_2")
        self.verticalLayout_3.addWidget(self.pushButton_3_2, 0, QtCore.Qt.AlignTop)
        self.pushButton_3_3 = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_3_3.setObjectName("pushButton_3_3")
        self.verticalLayout_3.addWidget(self.pushButton_3_3, 0, QtCore.Qt.AlignTop)
        self.pushButton_3_4 = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_3_4.setObjectName("pushButton_3_4")
        self.verticalLayout_3.addWidget(self.pushButton_3_4, 0, QtCore.Qt.AlignTop)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(600, 30, 160, 521))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4, 0, QtCore.Qt.AlignTop)
        self.pushButton_4_1 = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.pushButton_4_1.setObjectName("pushButton_4_1")
        self.verticalLayout_4.addWidget(self.pushButton_4_1, 0, QtCore.Qt.AlignTop)
        self.pushButton_4_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.pushButton_4_2.setObjectName("pushButton_4_2")
        self.verticalLayout_4.addWidget(self.pushButton_4_2, 0, QtCore.Qt.AlignTop)
        self.pushButton_4_3 = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.pushButton_4_3.setObjectName("pushButton_4_3")
        self.verticalLayout_4.addWidget(self.pushButton_4_3, 0, QtCore.Qt.AlignTop)
        self.pushButton_4_4 = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.pushButton_4_4.setObjectName("pushButton_4_4")
        self.verticalLayout_4.addWidget(self.pushButton_4_4, 0, QtCore.Qt.AlignTop)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "1. Image Processing"))
        self.pushButton_1_1.setText(_translate("MainWindow", "1.1 Load Image"))
        self.pushButton_1_2.setText(_translate("MainWindow", "1.2 Color Seperation"))
        self.pushButton_1_3.setText(_translate("MainWindow", "1.3 Color Transformation"))
        self.pushButton_1_4.setText(_translate("MainWindow", "1.4 Blending"))
        self.label_2.setText(_translate("MainWindow", "2. Image Smoothing"))
        self.pushButton_2_1.setText(_translate("MainWindow", "2.1 Gaussian Blur"))
        self.pushButton_2_2.setText(_translate("MainWindow", "2.2 Bilateral Filter"))
        self.pushButton_2_3.setText(_translate("MainWindow", "2.3 Median Filter"))
        self.label_3.setText(_translate("MainWindow", "3. Edge Detection"))
        self.pushButton_3_1.setText(_translate("MainWindow", "3.1 Gaussian Blur"))
        self.pushButton_3_2.setText(_translate("MainWindow", "3.2 Sobel X"))
        self.pushButton_3_3.setText(_translate("MainWindow", "3.3 Sobel Y"))
        self.pushButton_3_4.setText(_translate("MainWindow", "3.4 Magnitude"))
        self.label_4.setText(_translate("MainWindow", "4. Transforms"))
        self.pushButton_4_1.setText(_translate("MainWindow", "4.1 Resize"))
        self.pushButton_4_2.setText(_translate("MainWindow", "4.2 Translation"))
        self.pushButton_4_3.setText(_translate("MainWindow", "4.3 Rotation, Scaling"))
        self.pushButton_4_4.setText(_translate("MainWindow", "4.4 Shearing"))

